name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Build site
        run: npm run generate

      - name: Clear Wrangler credentials
        run: rm -rf ~/.wrangler

      - name: Install Wrangler
        run: npm install wrangler --save-dev

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=landing-page-one
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
