name: Production Release for all sites

on:
  push:
    tags:
      - 'release-*'

jobs:
  rebase-sites:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase site branches onto main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          SITE_BRANCHES=$(git ls-remote --heads origin | awk '{print $2}' | sed 's#refs/heads/##' | grep '^site')
          DATE_STR=$(date +'%Y%m%d%H%M%S')

          for BRANCH in $SITE_BRANCHES; do
            echo "🔁 Attempting to rebase $BRANCH onto main..."

            git fetch origin $BRANCH
            git checkout -B $BRANCH origin/$BRANCH

            git rebase origin/main
            echo "✅ Rebase successful for $BRANCH"

            git push origin $BRANCH --force-with-lease
          done
