name: Site 1 Production Release

on:
  push:
    tags:
      - 'site1-*'

jobs:
  rebase-sites:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase site branch onto main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          BRANCH="site1"

          echo "🔁 Attempting to rebase $BRANCH onto main..."

          git fetch origin $BRANCH
          git checkout -B $BRANCH origin/$BRANCH

          git rebase origin/main
          echo "✅ Rebase successful for $BRANCH"

          git push origin $BRANCH --force-with-lease
