name: Rebase site branches onto main

on:
  push:
    branches:
      - main

jobs:
  rebase-sites:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for full branch history

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase site branches onto main with auto-conflict PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          SITE_BRANCHES=$(git ls-remote --heads origin | awk '{print $2}' | sed 's#refs/heads/##' | grep '^site')
          DATE=$(date +%Y%m%d)

          for BRANCH in $SITE_BRANCHES; do
            echo "🔁 Attempting to rebase $BRANCH onto main..."

            git fetch origin $BRANCH
            git checkout -B $BRANCH origin/$BRANCH

            if git rebase origin/main; then
              echo "✅ Rebase successful for $BRANCH"
              git push origin $BRANCH --force-with-lease
            else
              echo "❌ Conflict during rebase of $BRANCH. Creating conflict branch..."

              git rebase --abort
              CONFLICT_BRANCH="conflict/${BRANCH}-${DATE}"
              git checkout -b "$CONFLICT_BRANCH"

              # Merge main into conflict branch
              git merge origin/main || true

              # Check if there are real changes
              TARGET_BRANCH="$BRANCH"
              git fetch origin "$TARGET_BRANCH"
              git checkout "$TARGET_BRANCH"
              git merge --no-commit --no-ff "$CONFLICT_BRANCH"

              if git diff --quiet && git diff --cached --quiet; then
                echo "✅ No actual changes in $CONFLICT_BRANCH. Auto-merging into $TARGET_BRANCH..."
                git commit -m "Auto-merged clean conflict branch $CONFLICT_BRANCH into $TARGET_BRANCH"
                git push origin "$TARGET_BRANCH"
                echo "✅ Auto-merge complete for $TARGET_BRANCH"
              else
                echo "⚠️ Changes found in $CONFLICT_BRANCH. Pushing and creating PR..."
                git checkout "$CONFLICT_BRANCH"
                git push origin "$CONFLICT_BRANCH"

                gh pr create \
                  --title "Conflict: Rebase of $BRANCH with main" \
                  --body "This branch contains merge conflicts that need to be resolved manually." \
                  --head "$CONFLICT_BRANCH" \
                  --base "$BRANCH"
              fi
            fi
          done
