name: Rebase site branches onto main

on:
  push:
    branches:
      - main

jobs:
  rebase-sites:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase site branches onto main with auto-conflict PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          SITE_BRANCHES=$(git ls-remote --heads origin | awk '{print $2}' | sed 's#refs/heads/##' | grep '^site')
          DATE_STR=$(date +'%Y%m%d%H%M%S')

          for BRANCH in $SITE_BRANCHES; do
            echo "🔁 Attempting to rebase $BRANCH onto main..."

            git fetch origin $BRANCH
            git checkout -B $BRANCH origin/$BRANCH

            if git rebase origin/main; then
              echo "✅ Rebase successful for $BRANCH"
              git push origin $BRANCH --force-with-lease
            else
              echo "❌ Conflict during rebase of $BRANCH. Creating conflict branch & PR..."

              git rebase --abort
              CONFLICT_BRANCH="conflict/${BRANCH}-${DATE_STR}"
              git checkout -b "$CONFLICT_BRANCH"

              # Attempt merge to capture the conflict
              git merge origin/main || true

              # Stage all resolved conflicts if needed
              git add -A

              # Commit if there are any changes
              if ! git diff --cached --quiet; then
                git commit -m "Conflict branch for $BRANCH"
              fi

              # Push the conflict branch with a unique name
              git push origin "$CONFLICT_BRANCH"

              # Create pull request for manual resolution
              gh pr create \
                --title "Conflict: Rebase of $BRANCH with main" \
                --body "This branch contains merge conflicts that need to be resolved manually." \
                --head "$CONFLICT_BRANCH" \
                --base "$BRANCH"
            fi
          done
