name: Rebase site branches onto main

on:
  push:
    branches:
      - main

jobs:
  rebase-sites:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for full branch history

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase site branches onto main with auto-conflict PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          SITE_BRANCHES=$(git ls-remote --heads origin | awk '{print $2}' | sed 's#refs/heads/##' | grep '^site')
          DATE=$(date +%Y%m%d)

          for BRANCH in $SITE_BRANCHES; do
            echo "🔁 Attempting to rebase $BRANCH onto main..."

            git fetch origin $BRANCH
            git checkout -B $BRANCH origin/$BRANCH

            if git rebase origin/main; then
              echo "✅ Rebase successful for $BRANCH"
              git push origin $BRANCH --force-with-lease
            else
              echo "❌ Conflict during rebase of $BRANCH. Creating conflict branch & PR..."

              git rebase --abort
              CONFLICT_BRANCH="conflict/${BRANCH}-${DATE}"
              git checkout -b "$CONFLICT_BRANCH"
              git push origin "$CONFLICT_BRANCH"

              gh pr create \
                --base "$BRANCH" \
                --head "$CONFLICT_BRANCH" \
                --title "🚨 Conflict: Rebase $BRANCH onto main" \
                --body "This PR was auto-generated because rebasing \`$BRANCH\` onto \`main\` resulted in a conflict. Please resolve manually, then merge to update the branch."
            fi
          done
